In [1]:
import numpy as np
import pandas as pd
#content based

In [2]:
data=pd.read_csv('netflix_titles.csv')

In [3]:
cols=data.columns

# PREPROCESSING

In [4]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [5]:
data=data.dropna()
data=data.reset_index()

In [6]:
data.isnull().sum()

index           0
show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [7]:
data.head()

,index,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
1,8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
2,9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
3,12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
4,24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

In [8]:
data

,index,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
1,8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
2,9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
3,12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
4,24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5327,8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
5328,8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
5329,8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
5330,8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
5331,8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [9]:
cols

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [10]:
#title
#cast
#rating
#description
#director
#release_year
#listed_in
#duration

In [11]:
df=data[['title','cast','rating','director','description','release_year','listed_in','show_id']]

In [12]:
df.duplicated().sum()

0

In [13]:
df['listed_in'].values

array(['Dramas, Independent Movies, International Movies',
       'British TV Shows, Reality TV', 'Comedies, Dramas', ...,
       'Comedies, Horror Movies', 'Children & Family Movies, Comedies',
       'Dramas, International Movies, Music & Musicals'], dtype=object)

In [14]:
df['rating'].values

array(['TV-MA', 'TV-14', 'PG-13', ..., 'R', 'PG', 'TV-14'], dtype=object)

In [15]:
df

,title,cast,rating,director,description,release_year,listed_in,show_id
0,Sankofa,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...",TV-MA,Haile Gerima,"On a photo shoot in Ghana, an American model s...",1993,"Dramas, Independent Movies, International Movies",s8
1,The Great British Baking Show,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",TV-14,Andy Devonshire,A talented batch of amateur bakers face off in...,2021,"British TV Shows, Reality TV",s9
2,The Starling,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",PG-13,Theodore Melfi,A woman adjusting to life after a loss contend...,2021,"Comedies, Dramas",s10
3,Je Suis Karl,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ...",TV-MA,Christian Schwochow,After most of her family is murdered in a terr...,2021,"Dramas, International Movies",s13
4,Jeans,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",TV-14,S. Shankar,When the father of the man she loves insists t...,1998,"Comedies, International Movies, Romantic Movies",s25
...,...,...,...,...,...,...,...,...
5327,Zinzana,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...",TV-MA,Majid Al Ansari,Recovering alcoholic Talal wakes up inside a s...,2015,"Dramas, International Movies, Thrillers",s8802
5328,Zodiac,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",R,David Fincher,"A political cartoonist, a crime reporter and a...",2007,"Cult Movies, Dramas, Thrillers",s8803
5329,Zombieland,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",R,Ruben Fleischer,Looking to survive in a world taken over by zo...,2009,"Comedies, Horror Movies",s8805
5330,Zoom,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",PG,Peter Hewitt,"Dragged from civilian life, a former superhero...",2006,"Children & Family Movies, Comedies",s8806
5331,Zubaan,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",TV-14,Mozez Singh,A scrappy but poor boy worms his way into a ty...,2015,"Dramas, International Movies, Music & Musicals",s8807

In [16]:
df['description'][0:1]

0    On a photo shoot in Ghana, an American model s...
Name: description, dtype: object

In [17]:
x=df['cast'][0:1]

In [18]:
#df['cast']=df['cast'].apply(lambda x:[i.replace(".","")for i in x])

In [19]:
for i in x:
    print(x)

0    Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
Name: cast, dtype: object

# TARGET

In [20]:
df['tags']=df['cast']+df['listed_in']+df['director']+df['description']

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11392\1810983160.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['cast']+df['listed_in']+df['director']+df['description']

In [21]:
df

,title,cast,rating,director,description,release_year,listed_in,show_id,tags
0,Sankofa,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...",TV-MA,Haile Gerima,"On a photo shoot in Ghana, an American model s...",1993,"Dramas, Independent Movies, International Movies",s8,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D..."
1,The Great British Baking Show,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",TV-14,Andy Devonshire,A talented batch of amateur bakers face off in...,2021,"British TV Shows, Reality TV",s9,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho..."
2,The Starling,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",PG-13,Theodore Melfi,A woman adjusting to life after a loss contend...,2021,"Comedies, Dramas",s10,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T..."
3,Je Suis Karl,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ...",TV-MA,Christian Schwochow,After most of her family is murdered in a terr...,2021,"Dramas, International Movies",s13,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ..."
4,Jeans,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",TV-14,S. Shankar,When the father of the man she loves insists t...,1998,"Comedies, International Movies, Romantic Movies",s25,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi..."
...,...,...,...,...,...,...,...,...,...
5327,Zinzana,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...",TV-MA,Majid Al Ansari,Recovering alcoholic Talal wakes up inside a s...,2015,"Dramas, International Movies, Thrillers",s8802,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ..."
5328,Zodiac,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",R,David Fincher,"A political cartoonist, a crime reporter and a...",2007,"Cult Movies, Dramas, Thrillers",s8803,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J..."
5329,Zombieland,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",R,Ruben Fleischer,Looking to survive in a world taken over by zo...,2009,"Comedies, Horror Movies",s8805,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ..."
5330,Zoom,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",PG,Peter Hewitt,"Dragged from civilian life, a former superhero...",2006,"Children & Family Movies, Comedies",s8806,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma..."
5331,Zubaan,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",TV-14,Mozez Singh,A scrappy but poor boy worms his way into a ty...,2015,"Dramas, International Movies, Music & Musicals",s8807,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan..."

In [22]:
df['tags']

0       Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
1       Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...
2       Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
3       Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ...
4       Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...
                              ...
5327    Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...
5328    Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
5329    Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
5330    Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
5331    Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
Name: tags, Length: 5332, dtype: object

In [23]:
data['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

In [24]:
new_df=df[['title','tags','show_id']]

In [25]:
new_df

,title,tags,show_id
0,Sankofa,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...",s8
1,The Great British Baking Show,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",s9
2,The Starling,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",s10
3,Je Suis Karl,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ...",s13
4,Jeans,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",s25
...,...,...,...
5327,Zinzana,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...",s8802
5328,Zodiac,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",s8803
5329,Zombieland,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",s8805
5330,Zoom,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",s8806
5331,Zubaan,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",s8807

In [26]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11392\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [27]:
new_df['tags']

0       kofi ghanaba, oyafunmike ogunlano, alexandra d...
1       mel giedroyc, sue perkins, mary berry, paul ho...
2       melissa mccarthy, chris o'dowd, kevin kline, t...
3       luna wedler, jannis niewÃ¶hner, milan peschel, ...
4       prashanth, aishwarya rai bachchan, sri lakshmi...
                              ...
5327    ali suliman, saleh bakri, yasa, ali al-jabri, ...
5328    mark ruffalo, jake gyllenhaal, robert downey j...
5329    jesse eisenberg, woody harrelson, emma stone, ...
5330    tim allen, courteney cox, chevy chase, kate ma...
5331    vicky kaushal, sarah-jane dias, raaghav chanan...
Name: tags, Length: 5332, dtype: object

In [28]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [29]:
# def stem(text):
#     y=[]
#     for i in text.split():
#         y.append(ps.stem(i))
#     return "".join(y)

In [30]:
# new_df['tags']=new_df['tags'].apply(stem)

In [31]:
new_df['tags']

0       kofi ghanaba, oyafunmike ogunlano, alexandra d...
1       mel giedroyc, sue perkins, mary berry, paul ho...
2       melissa mccarthy, chris o'dowd, kevin kline, t...
3       luna wedler, jannis niewÃ¶hner, milan peschel, ...
4       prashanth, aishwarya rai bachchan, sri lakshmi...
                              ...
5327    ali suliman, saleh bakri, yasa, ali al-jabri, ...
5328    mark ruffalo, jake gyllenhaal, robert downey j...
5329    jesse eisenberg, woody harrelson, emma stone, ...
5330    tim allen, courteney cox, chevy chase, kate ma...
5331    vicky kaushal, sarah-jane dias, raaghav chanan...
Name: tags, Length: 5332, dtype: object

# TARGET VECTORIZATION

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
cv = CountVectorizer(max_features=4000,stop_words='english')

In [34]:
cv

CountVectorizer(max_features=4000, stop_words='english')

In [35]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [36]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
cv.get_feature_names_out()

array(['000', '10', '11', ..., 'zoe', 'Ã¡lvaro', 'Ã¡ngel'], dtype=object)

In [38]:
cv.vocabulary_

{'alexandra': 112,
 'nick': 2568,
 'reggie': 2977,
 'carter': 525,
 'independent': 1672,
 'movies': 2443,
 'international': 1699,
 'american': 141,
 'model': 2409,
 'time': 3625,
 'past': 2696,
 'mel': 2342,
 'sue': 3489,
 'mary': 2291,
 'berry': 348,
 'paul': 2710,
 'tv': 3710,
 'shows': 3306,
 'reality': 2947,
 'talented': 3553,
 'face': 1165,
 '10': 1,
 'week': 3875,
 'competition': 717,
 'best': 349,
 'hopes': 1594,
 'named': 2518,
 'melissa': 2344,
 'mccarthy': 2320,
 'chris': 627,
 'dowd': 987,
 'kevin': 1936,
 'timothy': 3627,
 'laura': 2048,
 'chao': 579,
 'kimberly': 1963,
 'quinn': 2877,
 'loretta': 2161,
 'devine': 924,
 'ravi': 2938,
 'kapoorcomedies': 1887,
 'woman': 3926,
 'life': 2110,
 'loss': 2167,
 'bird': 370,
 'taken': 3547,
 'garden': 1336,
 'husband': 1634,
 'struggling': 3469,
 'way': 3861,
 'forward': 1283,
 'luna': 2195,
 'milan': 2374,
 'anna': 178,
 'marlon': 2272,
 'victor': 3789,
 'aziz': 277,
 'mÃ©lanie': 2510,
 'family': 1183,
 'murdered': 2496,
 'terrorist': 3593,
 'young': 3974,
 'lured': 2197,
 'joining': 1817,
 'group': 1446,
 'killed': 1959,
 'aishwarya': 92,
 'rai': 2896,
 'bachchan': 282,
 'lakshmi': 2025,
 'romantic': 3092,
 'father': 1202,
 'man': 2241,
 'loves': 2178,
 'twin': 3711,
 'sons': 3371,
 'marry': 2277,
 'sisters': 3337,
 'creates': 769,
 'alter': 132,
 'ego': 1045,
 'adam': 48,
 'sandler': 3164,
 'james': 1754,
 'rock': 3078,
 'david': 850,
 'rob': 3066,
 'schneider': 3196,
 'salma': 3151,
 'hayek': 1514,
 'maria': 2262,
 'bello': 331,
 'maya': 2315,
 'rudolph': 3116,
 'colin': 684,
 'tim': 3624,
 'joyce': 1841,
 'van': 3764,
 'beloved': 332,
 'junior': 1863,
 'high': 1556,
 'basketball': 305,
 'coach': 676,
 'middle': 2369,
 'aged': 74,
 'pals': 2673,
 'reunite': 3015,
 'lake': 2024,
 'house': 1610,
 'kid': 1950,
 'russell': 3128,
 'josh': 1833,
 'hamilton': 1480,
 'simmons': 3324,
 'dakota': 813,
 'rich': 3031,
 'annie': 181,
 'thurman': 3619,
 'jake': 1750,
 'sci': 3200,
 'fi': 1226,
 'suburban': 3483,
 'alien': 121,
 'force': 1270,
 'home': 1586,
 'struggle': 3467,
 'deadly': 858,
 'threat': 3610,
 'liam': 2104,
 'hemsworth': 1541,
 'gary': 1341,
 'oldman': 2619,
 'amber': 135,
 'heard': 1522,
 'harrison': 1500,
 'ford': 1274,
 'lucas': 2185,
 'till': 3623,
 'julian': 1852,
 'richard': 3032,
 'angela': 164,
 'company': 715,
 'ceo': 558,
 'low': 2180,
 'level': 2094,
 'employee': 1085,
 'finds': 1246,
 'forced': 1271,
 'spy': 3405,
 'boss': 406,
 'rival': 3059,
 'mentor': 2355,
 'billy': 366,
 'ron': 3094,
 'terry': 3595,
 'chen': 601,
 'wu': 3949,
 'jin': 1798,
 'philip': 2749,
 'ng': 2562,
 'yu': 3979,
 'adventure': 63,
 'bruce': 456,
 'lee': 2072,
 'kung': 2012,
 'fu': 1310,
 'leading': 2061,
 'master': 2297,
 'film': 1238,
 'based': 304,
 'real': 2945,
 'events': 1139,
 'roy': 3112,
 'robert': 3071,
 'shaw': 3282,
 'lorraine': 2162,
 'murray': 2500,
 'carl': 512,
 'jeffrey': 1771,
 'susan': 3523,
 'jonathan': 1824,
 'ted': 3577,
 'classic': 658,
 'great': 1424,
 'white': 3890,
 'shark': 3275,
 'island': 1725,
 'police': 2790,
 'chief': 609,
 'hunter': 1631,
 'seek': 3220,
 'destroy': 916,
 'joseph': 1832,
 'paxton': 2717,
 'ann': 177,
 'mark': 2270,
 'barry': 303,
 'horror': 1598,
 'years': 3962,
 'martin': 2286,
 'brody': 446,
 'fights': 1235,
 'protect': 2850,
 'killer': 1960,
 'dennis': 895,
 'quaid': 2869,
 'armstrong': 214,
 'simon': 3325,
 'louis': 2172,
 'jr': 1842,
 'john': 1811,
 'lea': 2058,
 'thompson': 3607,
 'dan': 823,
 'liz': 2135,
 'morris': 2433,
 'lisa': 2127,
 'staff': 3411,
 'marine': 2267,
 'park': 2686,
 'try': 3696,
 'capture': 502,
 'discover': 950,
 'mother': 2437,
 'blood': 384,
 'lance': 2029,
 'guest': 1452,
 'mario': 2268,
 'karen': 1893,
 'michael': 2364,
 'judith': 1848,
 'mitchell': 2401,
 'anderson': 156,
 'lynn': 2201,
 'attack': 251,
 'ellen': 1068,
 'moves': 2441,
 'follows': 1264,
 'denzel': 896,
 'washington': 3856,
 'ryan': 3133,
 'reynolds': 3024,
 'vera': 3777,
 'farmiga': 1196,
 'brendan': 425,
 'gleeson': 1387,
 'sam': 3153,
 'shepard': 3290,
 'nora': 2589,
 'patrick': 2707,
 'joel': 1808,
 'cia': 640,
 'matt': 2306,
 'weston': 3887,
 'dangerous': 829,
 'criminal': 777,
 'agency': 75,
 'come': 694,
 'ethan': 1127,
 'scott': 3205,
 'glenn': 1388,
 'tom': 3635,
 'harris': 1499,
 'raymond': 2942,
 'cliff': 669,
 'curtis': 801,
 'dr': 989,
 'snoop': 3348,
 'macy': 2212,
 'gray': 1423,
 'eva': 1132,
 'rookie': 3096,
 'cop': 746,
 'day': 855,
 'prove': 2851,
 'veteran': 3783,
 'officer': 2613,
 'receives': 2955,
 'crash': 766,
 'course': 760,
 'brand': 417,
 'justice': 1866,
 'yamaguchi': 3955,
 'satsuki': 3181,
 'yukino': 3983,
 'koji': 1991,
 'houko': 1606,
 'kuwashima': 2014,
 'kumiko': 2009,
 'watanabe': 3857,
 'noriko': 2590,
 'anime': 172,
 'features': 1209,
 'biggest': 364,
 'foe': 1261,
 'seemingly': 3224,
 'friends': 1306,
 'return': 3011,
 'peace': 2720,
 'soon': 3373,
 'shattered': 3280,
 'new': 2556,
 'enemy': 1094,
 'ken': 1928,
 'dog': 969,
 'demon': 891,
 'fang': 1186,
 'evil': 1142,
 'power': 2808,
 'sword': 3534,
 'cho': 620,
 'half': 1476,
 'escaped': 1121,
 'help': 1538,
 'people': 2729,
 'returns': 3013,
 'potential': 2805,
 'powerful': 2809,
 'away': 273,
 'son': 3362,
 'fate': 1201,
 'world': 3941,
 'junko': 1864,
 'takeuchi': 3549,
 'chie': 608,
 'nakamura': 2516,
 'koyama': 1997,
 'kazuhiko': 1916,
 'inoue': 1688,
 'accused': 38,
 'ninja': 2581,
 'imprisoned': 1665,
 'castle': 536,
 'powers': 2810,
 'nana': 2519,
 'strange': 3456,
 'village': 3801,
 'long': 2147,
 'missing': 2399,
 'pal': 2670,
 'save': 3184,
 'planet': 2773,
 'koichi': 1989,
 'leader': 2060,
 'tries': 3683,
 'true': 3691,
 'land': 2030,
 'daisuke': 811,
 'ono': 2631,
 'adventures': 64,
 'tasked': 3567,
 'die': 936,
 'kobayashi': 1984,
 'sent': 3238,
 'recover': 2963,
 '20': 9,
 'battle': 308,
 'akira': 96,
 'mission': 2400,
 'fellow': 1215,
 'brutal': 458,
 'led': 2071,
 'enigmatic': 1101,
 'teams': 3575,
 'prince': 2830,
 'moon': 2427,
 'kingdom': 1966,
 'jun': 1859,
 'learn': 2064,
 'll': 2137,
 'actress': 45,
 'hurt': 1633,
 'making': 2232,
 'turns': 3707,
 'princess': 2831,
 'sola': 3356,
 'adesua': 52,
 'etomi': 1128,
 'ejiofor': 1052,
 'toni': 3639,
 'sharon': 3278,
 'political': 2791,
 'ambitions': 136,
 'threatened': 3612,
 'underworld': 3730,
 'cost': 754,
 'elizabeth': 1065,
 'winstead': 3915,
 'woody': 3935,
 'harrelson': 1498,
 'nicolas': 2571,
 'fatal': 1200,
 'final': 1242,
 'job': 1804,
 'ruthless': 3132,
 'assassin': 246,
 'working': 3939,
 '24': 10,
 'hours': 1609,
 'ordered': 2636,
 'hit': 1570,
 'exact': 1145,
 'revenge': 3020,
 'ayo': 275,
 'makun': 2234,
 'blossom': 386,
 'chukwujekwu': 636,
 'tina': 3628,
 'mba': 2317,
 'femi': 1217,
 'comedies': 697,
 'good': 1405,
 'hearted': 1526,
 'female': 1216,
 'gangster': 1332,
 'sister': 3336,
 'crime': 775,
 'cops': 748,
 'trouble': 3687,
 'emma': 1080,
 'roberts': 3073,
 'danielle': 833,
 'macdonald': 2206,
 'gonzÃ¡lez': 1404,
 'jeremy': 1779,
 'daniel': 831,
 'fantasy': 1189,
 'wakes': 3834,
 'turn': 3703,
 'girls': 1383,
 'perfect': 2732,
 'bad': 285,
 'purpose': 2860,
 'ludacris': 2190,
 'natasha': 2527,
 'stanley': 3419,
 'tucci': 3698,
 'sparks': 3386,
 'gabriel': 1318,
 'iglesias': 1654,
 'neal': 2541,
 'omar': 2626,
 'alan': 101,
 'andy': 162,
 'kerry': 1935,
 'tough': 3648,
 'undercover': 3728,
 'fbi': 1206,
 'agent': 76,
 'baby': 281,
 'illegal': 1661,
 'ronnie': 3095,
 'allen': 127,
 'collins': 689,
 'leon': 2083,
 'bob': 390,
 'burns': 470,
 'powell': 2807,
 'ed': 1036,
 'king': 1965,
 'pyle': 2867,
 'steve': 3441,
 'johnny': 1812,
 'music': 2501,
 'interviews': 1702,
 'footage': 1267,
 'documentary': 966,
 'story': 3453,
 'legendary': 2076,
 'southern': 3381,
 'focus': 1260,
 'benjamin': 336,
 'kumar': 2007,
 'wilson': 3906,
 'davis': 852,
 'jose': 1831,
 'growing': 1448,
 'gang': 1331,
 'hometown': 1587,
 'vincent': 3806,
 'forms': 1280,
 'squad': 3406,
 'ends': 1091,
 'wrong': 3948,
 'law': 2054,
 'mandy': 2244,
 'grace': 1413,
 'donna': 977,
 'key': 1937,
 'isabella': 1721,
 'ariana': 209,
 'dramasdavid': 994,
 'grieving': 1439,
 'teen': 3578,
 'work': 3936,
 'debt': 867,
 'ranch': 2923,
 'horse': 1599,
 'healing': 1520,
 'madhuri': 2216,
 'dixit': 960,
 'shah': 3264,
 'rukh': 3119,
 'khan': 1941,
 'tinnu': 3630,
 'anand': 153,
 'johny': 1815,
 'lever': 2095,
 'himani': 1561,
 'shivpuri': 3300,
 'kiran': 1970,
 'wealthy': 3865,
 'obsession': 2606,
 'takes': 3548,
 'hands': 1483,
 'ben': 334,
 'fox': 1286,
 'thomas': 3606,
 'gerard': 1355,
 'antonia': 190,
 'campbell': 494,
 'hughes': 1620,
 'samuel': 3159,
 'drama': 992,
 'details': 917,
 'passionate': 2695,
 'year': 3961,
 'romance': 3091,
 'poet': 2786,
 'age': 73,
 'love': 2174,
 'vipin': 3811,
 'sharma': 3276,
 'suresh': 3511,
 'menon': 2353,
 'vijay': 3797,
 'rajiv': 2908,
 'dramas': 993,
 'movie': 2442,
 'loving': 2179,
 'old': 2617,
 'blind': 382,
 'little': 2129,
 'brother': 453,
 'meet': 2335,
 'indian': 1674,
 'superstar': 3508,
 'getting': 1361,
 'boy': 409,
 'eye': 1159,
 'akshay': 97,
 'oberoi': 2602,
 'pankaj': 2678,
 'tripathi': 3686,
 'khanna': 1944,
 'aamir': 14,
 'ashish': 234,
 'daughter': 848,
 'college': 686,
 'gets': 1360,
 'problems': 2837,
 'plans': 2774,
 'meg': 2338,
 'jennifer': 1775,
 'jason': 1763,
 'leigh': 2078,
 'bacon': 284,
 'heather': 1527,
 'affair': 66,
 'murder': 2495,
 'suspects': 3526,
 'lover': 2176,
 'involved': 1710,
 'chatterjee': 593,
 'ashwin': 241,
 'vinod': 3807,
 'couple': 758,
 'drive': 1003,
 'camp': 492,
 'chad': 560,
 'regina': 2978,
 'julie': 1854,
 'gonzalo': 1403,
 'lin': 2119,
 'madeline': 2215,
 'andrea': 158,
 'avery': 270,
 'pat': 2697,
 'rodriguez': 3082,
 'erica': 1115,
 'meets': 2337,
 'dreams': 999,
 'dance': 825,
 'returning': 3012,
 'lost': 2168,
 'cell': 552,
 'phone': 2753,
 'bring': 437,
 'lopez': 2156,
 'morgan': 2432,
 'freeman': 1302,
 'damian': 820,
 'lewis': 2100,
 'boyd': 410,
 'widow': 3894,
 'estranged': 1126,
 'heal': 1519,
 'sean': 3207,
 'edward': 1040,
 'walsh': 3841,
 'daryl': 844,
 'hannah': 1487,
 'william': 3900,
 'joe': 1807,
 'joanna': 1802,
 'cassidy': 532,
 'hong': 1589,
 'cult': 793,
 'dystopian': 1026,
 'los': 2163,
 'angeles': 165,
 'rick': 3036,
 'called': 486,
 'retirement': 3008,
 'hugh': 1619,
 'weaver': 3867,
 'dev': 920,
 'patel': 2699,
 'pablo': 2656,
 'brandon': 418,
 'maurice': 2311,
 'society': 3352,
 'robot': 3077,
 'keeps': 1922,
 'lone': 2144,
 'intelligence': 1697,
 'willem': 3899,
 'dafoe': 809,
 'anne': 179,
 'henry': 1544,
 'donald': 975,
 'miguel': 2370,
 'dean': 862,
 'jones': 1825,
 'earl': 1029,
 'president': 2822,
 'friend': 1305,
 'director': 946,
 'jack': 1735,
 'unwittingly': 3748,
 'war': 3849,
 'drug': 1007,
 'cartel': 524,
 'sylvester': 3536,
 'stallone': 3415,
 'turner': 3705,
 'caroline': 519,
 'craig': 765,
 'ralph': 2912,
 'max': 2313,
 'walker': 3837,
 'partner': 2690,
 'rescue': 2997,
 'stranded': 3455,
 'actually': 46,
 'jude': 1846,
 'nicole': 2572,
 'kidman': 1951,
 'renÃ©e': 2994,
 'eileen': 1050,
 'atkins': 250,
 'seymour': 3262,
 'hoffman': 1574,
 'natalie': 2526,
 'giovanni': 1379,
 'sutherland': 3528,
 'ray': 2941,
 'moviesanthony': 2448,
 'civil': 646,
 'soldier': 3358,
 'journey': 1838,
 'survival': 3518,
 'deceased': 869,
 'farm': 1194,
 'hogan': 1575,
 'linda': 2121,
 'banks': 300,
 'aida': 87,
 'turturro': 3708,
 'alec': 106,
 'grant': 1420,
 'mike': 2371,
 'mick': 2367,
 'lessons': 2088,
 'comedy': 701,
 'sequel': 3242,
 'channing': 578,
 'tatum': 3570,
 'amanda': 134,
 'jenkins': 1773,
 'moss': 2436,
 'keith': 1924,
 'robinson': 3076,
 'summer': 3499,
 'leave': 2068,
 'falls': 1180,
 'student': 3472,
 'letters': 2092,
 'hold': 1577,
 'lovers': 2177,
 'danny': 836,
 'ruby': 3114,
 'dee': 874,
 'giancarlo': 1367,
 'esposito': 1124,
 'frankie': 1296,
 'faison': 1174,
 'jackson': 1738,
 'rosie': 3108,
 'perez': 2731,
 'lawrence': 2055,
 'brooklyn': 450,
 'racial': 2884,
 'tensions': 3587,
 'residents': 2999,
 'rise': 3049,
 'surface': 3512,
 'violence': 3809,
 'tragedy': 3659,
 'joaquÃ­n': 1803,
 'luis': 2191,
 'guillermo': 1455,
 'mÃ³nica': 2511,
 'silva': 3321,
 'victoria': 3790,
 'lawyer': 2056,
 'cruel': 787,
 'case': 528,
 'willis': 3904,
 'kellan': 1925,
 'lutz': 2198,
 'gina': 1378,
 'joshua': 1835,
 'retired': 3007,
 'kidnapped': 1953,
 'government': 1411,
 'embarks': 1075,
 'plot': 2783,
 'hernandez': 1546,
 'kristin': 2002,
 'herrera': 1550,
 'sergio': 3243,
 'finn': 1247,
 'wyatt': 3950,
 'risk': 3053,
 'students': 3473,
 'frank': 1295,
 'teacher': 3573,
 'asks': 243,
 'troubled': 3688,
 'lives': 2133,
 'blake': 379,
 'lively': 2132,
 'peter': 2743,
 'strong': 3466,
 'robbins': 3070,
 'jay': 1766,
 'sanders': 3163,
 'pilot': 2764,
 'hal': 1473,
 'jordan': 1827,
 'ring': 3047,
 'helps': 1540,
 'stop': 3449,
 'christopher': 633,
 'reid': 2980,
 'robin': 3075,
 'johnson': 1813,
 'anthony': 186,
 'lou': 2171,
 'kelly': 1926,
 'jo': 1800,
 'strict': 3462,
 'risks': 3054,
 'play': 2776,
 'big': 363,
 'experiences': 1151,
 'queen': 2870,
 'doug': 985,
 'goes': 1395,
 'money': 2421,
 'loses': 2165,
 'shady': 3263,
 'wild': 3897,
 'plan': 2771,
 'raise': 2898,
 'cash': 530,
 'edwards': 1041,
 'means': 2329,
 'bernie': 347,
 'mac': 2204,
 'tucker': 3699,
 'engaged': 1096,
 'bachelor': 283,
 'party': 2692,
 'comes': 707,
 'palmer': 2672,
 'knight': 1978,
 'tommy': 3636,
 'tiny': 3631,
 'helen': 1534,
 'witherspoon': 3923,
 'mia': 2362,
 'comediesmichael': 698,
 'epps': 1110,
 'nia': 2564,
 'pam': 2674,
 'hill': 1560,
 'harper': 1497,
 'weber': 3872,
 'veronica': 3780,
 'webb': 3870,
 'canada': 497,
 'don': 974,
 'harvey': 1505,
 'jermaine': 1780,
 'cole': 682,
 'poses': 2801,
 'dealer': 860,
 'lord': 2157,
 'caught': 545,
 'chou': 625,
 'suzuki': 3530,
 'wong': 3930,
 'chau': 594,
 'sang': 3167,
 'shawn': 3283,
 'yue': 3980,
 'chapman': 582,
 'chan': 570,
 'kenny': 1932,
 'moviesandrew': 2447,
 'lau': 2044,
 'wai': 3832,
 'delivers': 886,
 'race': 2880,
 'car': 505,
 'driver': 1004,
 'night': 2576,
 'jai': 1747,
 'brooks': 451,
 'luke': 2194,
 'beau': 317,
 'australian': 266,
 'brothers': 454,
 'sensation': 3236,
 'clash': 656,
 'dave': 849,
 'brian': 429,
 'henson': 1545,
 'children': 613,
 'jim': 1795,
 'sarah': 3175,
 'quest': 2871,
 'gael': 1322,
 'garcÃ­a': 1335,
 'bernal': 344,
 'vanessa': 3765,
 'redgrave': 2969,
 'franco': 1294,
 'luisa': 2192,
 'marina': 2266,
 'marcia': 2257,
 'letter': 2091,
 'tragic': 3660,
 'juliet': 1855,
 'italy': 1732,
 'search': 3209,
 'katie': 1907,
 'douglas': 986,
 'sara': 3174,
 'alexis': 113,
 'williamson': 3902,
 'academy': 32,
 'uncover': 3726,
 'training': 3664,
 'escape': 1120,
 'christina': 630,
 'penn': 2728,
 'al': 98,
 'ashley': 236,
 'clark': 653,
 'nelson': 2554,
 'make': 2230,
 'popular': 2799,
 'girlfriend': 1382,
 'miriam': 2391,
 'chin': 614,
 'wah': 3829,
 'yeung': 3966,
 'singh': 3330,
 'isabel': 1720,
 'cheung': 604,
 'ming': 2387,
 'chow': 626,
 'ho': 1572,
 'kong': 1992,
 'drives': 1005,
 'hard': 1493,
 'outside': 2651,
 'unlikely': 3744,
 'nicholson': 2567,
 'close': 673,
 'annette': 180,
 'pierce': 2761,
 'brosnan': 452,
 'short': 3304,
 'jessica': 1786,
 'parker': 2687,
 'lukas': 2193,
 'flying': 1258,
 'head': 1517,
 'earth': 1032,
 'united': 3739,
 'prepares': 2819,
 'learns': 2066,
 'coming': 709,
 'chadwick': 562,
 'gad': 1321,
 'kate': 1902,
 'hudson': 1617,
 'sterling': 3439,
 'brown': 455,
 'stevens': 3443,
 'cromwell': 782,
 'sharp': 3279,
 'roger': 3085,
 'smith': 3347,
 'biopic': 369,
 'marshall': 2282,
 'black': 377,
 'court': 761,
 'ashton': 239,
 'tara': 3565,
 'richter': 3035,
 'madsen': 2218,
 'jon': 1821,
 'koechner': 1986,
 'carmen': 516,
 'terence': 3588,
 'molly': 2418,
 'moviesdavid': 2454,
 'hoping': 1595,
 'use': 3753,
 'opportunity': 2634,
 'win': 3907,
 'heart': 1524,
 'crush': 789,
 'stiller': 3446,
 'hank': 1485,
 'wes': 3882,
 'greg': 1432,
 'kinnear': 1969,
 'geoffrey': 1350,
 'rush': 3127,
 'lena': 2079,
 'eddie': 1037,
 'claire': 649,
 'team': 3574,
 'far': 1190,
 'super': 3504,
 'heroes': 1549,
 'earn': 1031,
 'action': 41,
 'brave': 419,
 'captain': 501,
 'disappears': 948,
 'niro': 2583,
 'woods': 3934,
 'williams': 3901,
 'burt': 472,
 'epic': 1109,
 'jewish': 1790,
 'york': 3973,
 'city': 645,
 'jane': 1757,
 'connolly': 730,
 'crispin': 780,
 'glover': 1393,
 'georgia': 1352,
 'bader': 286,
 'cody': 680,
 'cameron': 490,
 'fred': 1298,
 'olivia': 2622,
 'todd': 3634,
 'forest': 1275,
 'spoiled': 3400,
 'bent': 341,
 'laurence': 2050,
 ...}

In [39]:
vectors.shape#movie*top 4000words

(5332, 4000)

now we will calculate distance between recent movie to all the movies.
***
if distance is large then there is less similarity and vice-versa.
***
but here we will cal angle between them
hence we have to cal similarity of each movie to the every other movies.
***

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
similarity=cosine_similarity(vectors)

In [42]:
similarity.shape

(5332, 5332)

In [43]:
similarity

array([[1.        , 0.        , 0.        , ..., 0.        , 0.06154575,
        0.18463724],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.04351941, 0.08333333,
        0.04166667],
       ...,
       [0.        , 0.        , 0.04351941, ..., 1.        , 0.04351941,
        0.        ],
       [0.06154575, 0.        , 0.08333333, ..., 0.04351941, 1.        ,
        0.08333333],
       [0.18463724, 0.        , 0.04166667, ..., 0.        , 0.08333333,
        1.        ]])

In [44]:
new_df[new_df['title']=='Jeans'].index[0]#finding index of any movie in dataset

4

In [45]:
list(enumerate(similarity[0]))#store the index of movie

[(0, 1.0),
 (1, 0.0),
 (2, 0.0),
 (3, 0.07312724241271307),
 (4, 0.1315903389919538),
 (5, 0.0),
 (6, 0.0657951694959769),
 (7, 0.0),
 (8, 0.0),
 (9, 0.05698028822981897),
 (10, 0.05802588531856595),
 (11, 0.05698028822981897),
 (12, 0.05598925109558543),
 (13, 0.0),
 (14, 0.0),
 (15, 0.061545745489666376),
 (16, 0.0657951694959769),
 (17, 0.06030226891555273),
 (18, 0.061545745489666376),
 (19, 0.06741998624632421),
 (20, 0.06741998624632421),
 (21, 0.07106690545187015),
 (22, 0.06030226891555273),
 (23, 0.13834289277321493),
 (24, 0.07106690545187015),
 (25, 0.07312724241271307),
 (26, 0.06917144638660747),
 (27, 0.07537783614444091),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.059131239598908265),
 (32, 0.0),
 (33, 0.0),
 (34, 0.07312724241271307),
 (35, 0.12856486930664499),
 (36, 0.0),
 (37, 0.05598925109558543),
 (38, 0.1421338109037403),
 (39, 0.06741998624632421),
 (40, 0.13483997249264842),
 (41, 0.053300179088902604),
 (42, 0.06741998624632421),
 (43, 0.051708768999501914),
 (44, 0.0),
 (45, 0.0),
 (46, 0.0),
 (47, 0.0),
 (48, 0.05415303610738824),
 (49, 0.0),
 (50, 0.053300179088902604),
 (51, 0.13834289277321493),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.051708768999501914),
 (57, 0.0),
 (58, 0.0),
 (59, 0.0),
 (60, 0.052486388108147805),
 (61, 0.0778498944161523),
 (62, 0.05598925109558543),
 (63, 0.059131239598908265),
 (64, 0.0),
 (65, 0.0657951694959769),
 (66, 0.059131239598908265),
 (67, 0.051708768999501914),
 (68, 0.0),
 (69, 0.0),
 (70, 0.0),
 (71, 0.05698028822981897),
 (72, 0.061545745489666376),
 (73, 0.05698028822981897),
 (74, 0.0),
 (75, 0.0),
 (76, 0.0),
 (77, 0.0),
 (78, 0.08362420100070908),
 (79, 0.06030226891555273),
 (80, 0.0),
 (81, 0.0),
 (82, 0.0),
 (83, 0.0),
 (84, 0.0),
 (85, 0.0),
 (86, 0.0),
 (87, 0.08058229640253803),
 (88, 0.08058229640253803),
 (89, 0.05504818825631803),
 (90, 0.06286946134619315),
 (91, 0.06428243465332249),
 (92, 0.050251890762960605),
 (93, 0.07537783614444091),
 (94, 0.1421338109037403),
 (95, 0.10497277621629561),
 (96, 0.12060453783110546),
 (97, 0.05802588531856595),
 (98, 0.061545745489666376),
 (99, 0.1257389226923863),
 (100, 0.21320071635561044),
 (101, 0.1257389226923863),
 (102, 0.1315903389919538),
 (103, 0.16796775328675628),
 (104, 0.1556997888323046),
 (105, 0.13483997249264842),
 (106, 0.04397994971335425),
 (107, 0.1257389226923863),
 (108, 0.06286946134619315),
 (109, 0.1421338109037403),
 (110, 0.0),
 (111, 0.0),
 (112, 0.061545745489666376),
 (113, 0.0),
 (114, 0.15512630699850574),
 (115, 0.16724840200141816),
 (116, 0.09090909090909091),
 (117, 0.052486388108147805),
 (118, 0.12856486930664499),
 (119, 0.07312724241271307),
 (120, 0.05802588531856595),
 (121, 0.0),
 (122, 0.0),
 (123, 0.0),
 (124, 0.06917144638660747),
 (125, 0.23652495839563306),
 (126, 0.0),
 (127, 0.1160517706371319),
 (128, 0.061545745489666376),
 (129, 0.1315903389919538),
 (130, 0.0),
 (131, 0.0),
 (132, 0.06917144638660747),
 (133, 0.2842676218074806),
 (134, 0.05598925109558543),
 (135, 0.07312724241271307),
 (136, 0.1257389226923863),
 (137, 0.0),
 (138, 0.13834289277321493),
 (139, 0.05802588531856595),
 (140, 0.0),
 (141, 0.0),
 (142, 0.13483997249264842),
 (143, 0.0657951694959769),
 (144, 0.0),
 (145, 0.05415303610738824),
 (146, 0.07106690545187015),
 (147, 0.0),
 (148, 0.0),
 (149, 0.0),
 (150, 0.06030226891555273),
 (151, 0.059131239598908265),
 (152, 0.05598925109558543),
 (153, 0.0),
 (154, 0.05698028822981897),
 (155, 0.04891159880445185),
 (156, 0.0),
 (157, 0.04891159880445185),
 (158, 0.0),
 (159, 0.0),
 (160, 0.06428243465332249),
 (161, 0.059131239598908265),
 (162, 0.0),
 (163, 0.059131239598908265),
 (164, 0.0),
 (165, 0.0),
 (166, 0.0),
 (167, 0.0),
 (168, 0.0),
 (169, 0.06286946134619315),
 (170, 0.0),
 (171, 0.0),
 (172, 0.0),
 (173, 0.11396057645963795),
 (174, 0.0),
 (175, 0.0),
 (176, 0.0),
 (177, 0.2075143391598224),
 (178, 0.12856486930664499),
 (179, 0.07106690545187015),
 (180, 0.0),
 (181, 0.06286946134619315),
 (182, 0.18181818181818182),
 (183, 0.0),
 (184, 0.06030226891555273),
 (185, 0.0),
 (186, 0.0),
 (187, 0.0),
 (188, 0.0),
 (189, 0.14625448482542613),
 (190, 0.08362420100070908),
 (191, 0.13834289277321493),
 (192, 0.0),
 (193, 0.19069251784911848),
 (194, 0.1257389226923863),
 (195, 0.0),
 (196, 0.0),
 (197, 0.0),
 (198, 0.0),
 (199, 0.0),
 (200, 0.0),
 (201, 0.06741998624632421),
 (202, 0.061545745489666376),
 (203, 0.15075567228888181),
 (204, 0.06286946134619315),
 (205, 0.0),
 (206, 0.053300179088902604),
 (207, 0.10050378152592121),
 (208, 0.0),
 (209, 0.0),
 (210, 0.0),
 (211, 0.06428243465332249),
 (212, 0.1160517706371319),
 (213, 0.059131239598908265),
 (214, 0.07537783614444091),
 (215, 0.0778498944161523),
 (216, 0.0657951694959769),
 (217, 0.13834289277321493),
 (218, 0.061545745489666376),
 (219, 0.0778498944161523),
 (220, 0.08362420100070908),
 (221, 0.0657951694959769),
 (222, 0.07106690545187015),
 (223, 0.1257389226923863),
 (224, 0.1556997888323046),
 (225, 0.1160517706371319),
 (226, 0.1574591643244434),
 (227, 0.06286946134619315),
 (228, 0.0),
 (229, 0.0),
 (230, 0.06030226891555273),
 (231, 0.0),
 (232, 0.05504818825631803),
 (233, 0.05096471914376255),
 (234, 0.0),
 (235, 0.0),
 (236, 0.05504818825631803),
 (237, 0.1160517706371319),
 (238, 0.13483997249264842),
 (239, 0.053300179088902604),
 (240, 0.05598925109558543),
 (241, 0.0),
 (242, 0.07537783614444091),
 (243, 0.0),
 (244, 0.053300179088902604),
 (245, 0.0),
 (246, 0.0),
 (247, 0.0),
 (248, 0.0),
 (249, 0.0),
 (250, 0.12856486930664499),
 (251, 0.0),
 (252, 0.0),
 (253, 0.04956815970966097),
 (254, 0.0),
 (255, 0.06917144638660747),
 (256, 0.07106690545187015),
 (257, 0.0),
 (258, 0.0),
 (259, 0.06030226891555273),
 (260, 0.0),
 (261, 0.059131239598908265),
 (262, 0.06030226891555273),
 (263, 0.06286946134619315),
 (264, 0.0),
 (265, 0.0),
 (266, 0.059131239598908265),
 (267, 0.06286946134619315),
 (268, 0.0),
 (269, 0.0657951694959769),
 (270, 0.06286946134619315),
 (271, 0.06030226891555273),
 (272, 0.06428243465332249),
 (273, 0.13483997249264842),
 (274, 0.06030226891555273),
 (275, 0.0),
 (276, 0.06428243465332249),
 (277, 0.0),
 (278, 0.0),
 (279, 0.0778498944161523),
 (280, 0.1556997888323046),
 (281, 0.0),
 (282, 0.0),
 (283, 0.08058229640253803),
 (284, 0.07312724241271307),
 (285, 0.18181818181818182),
 (286, 0.08058229640253803),
 (287, 0.09090909090909091),
 (288, 0.0),
 (289, 0.061545745489666376),
 (290, 0.0),
 (291, 0.14625448482542613),
 (292, 0.09090909090909091),
 (293, 0.21320071635561044),
 (294, 0.0),
 (295, 0.052486388108147805),
 (296, 0.16116459280507606),
 (297, 0.07312724241271307),
 (298, 0.1315903389919538),
 (299, 0.0),
 (300, 0.1160517706371319),
 (301, 0.0),
 (302, 0.10660035817780521),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0),
 (306, 0.09090909090909091),
 (307, 0.10497277621629561),
 (308, 0.05698028822981897),
 (309, 0.05598925109558543),
 (310, 0.0),
 (311, 0.08362420100070908),
 (312, 0.06741998624632421),
 (313, 0.1315903389919538),
 (314, 0.06741998624632421),
 (315, 0.0),
 (316, 0.06428243465332249),
 (317, 0.22613350843332272),
 (318, 0.0),
 (319, 0.0657951694959769),
 (320, 0.16116459280507606),
 (321, 0.0),
 (322, 0.0),
 (323, 0.13834289277321493),
 (324, 0.17407765595569785),
 (325, 0.059131239598908265),
 (326, 0.0),
 (327, 0.07106690545187015),
 (328, 0.21320071635561041),
 (329, 0.15075567228888181),
 (330, 0.0),
 (331, 0.10830607221477648),
 (332, 0.0),
 (333, 0.1773937187967248),
 (334, 0.051708768999501914),
 (335, 0.0),
 (336, 0.14625448482542613),
 (337, 0.061545745489666376),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (342, 0.04264014327112209),
 (343, 0.0),
 (344, 0.0),
 (345, 0.07312724241271307),
 (346, 0.06741998624632421),
 (347, 0.0),
 (348, 0.0657951694959769),
 (349, 0.0),
 (350, 0.14625448482542613),
 (351, 0.0),
 (352, 0.0),
 (353, 0.0),
 (354, 0.06428243465332249),
 (355, 0.0),
 (356, 0.0),
 (357, 0.05504818825631803),
 (358, 0.06917144638660747),
 (359, 0.0),
 (360, 0.0),
 (361, 0.06030226891555273),
 (362, 0.0),
 (363, 0.0),
 (364, 0.07106690545187015),
 (365, 0.0),
 (366, 0.061545745489666376),
 (367, 0.0),
 (368, 0.09090909090909091),
 (369, 0.0),
 (370, 0.053300179088902604),
 (371, 0.2611164839335468),
 (372, 0.11396057645963795),
 (373, 0.18860838403857944),
 (374, 0.19738550848793068),
 (375, 0.05802588531856595),
 (376, 0.13483997249264842),
 (377, 0.0),
 (378, 0.059131239598908265),
 (379, 0.12309149097933275),
 (380, 0.0),
 (381, 0.0),
 (382, 0.07312724241271307),
 (383, 0.04828045495852676),
 (384, 0.11826247919781653),
 (385, 0.2193817272381392),
 (386, 0.2075143391598224),
 (387, 0.15075567228888181),
 (388, 0.05504818825631803),
 (389, 0.16116459280507606),
 (390, 0.05415303610738824),
 (391, 0.07312724241271307),
 (392, 0.1709408646894569),
 (393, 0.0),
 (394, 0.16796775328675628),
 (395, 0.23354968324845687),
 (396, 0.19284730395996746),
 (397, 0.18181818181818182),
 (398, 0.06741998624632421),
 (399, 0.08362420100070908),
 (400, 0.16724840200141816),
 (401, 0.0),
 (402, 0.06030226891555273),
 (403, 0.08058229640253803),
 (404, 0.2193817272381392),
 (405, 0.0),
 (406, 0.18463723646899913),
 (407, 0.0),
 (408, 0.13834289277321493),
 (409, 0.0),
 (410, 0.0),
 (411, 0.12309149097933275),
 (412, 0.06286946134619315),
 (413, 0.0),
 (414, 0.05698028822981897),
 (415, 0.0),
 (416, 0.0),
 (417, 0.0),
 (418, 0.06428243465332249),
 (419, 0.061545745489666376),
 (420, 0.04767312946227962),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.07312724241271307),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (429, 0.12060453783110546),
 (430, 0.0),
 (431, 0.0),
 (432, 0.0),
 (433, 0.07106690545187015),
 (434, 0.0657951694959769),
 (435, 0.10660035817780521),
 (436, 0.22613350843332272),
 (437, 0.0),
 (438, 0.08703882797784893),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.07106690545187015),
 (443, 0.18463723646899913),
 (444, 0.08703882797784893),
 (445, 0.08058229640253803),
 (446, 0.16116459280507606),
 (447, 0.07537783614444091),
 (448, 0.08703882797784893),
 (449, 0.07537783614444091),
 (450, 0.09090909090909091),
 (451, 0.14625448482542613),
 (452, 0.07106690545187015),
 (453, 0.15075567228888181),
 (454, 0.16724840200141816),
 (455, 0.0),
 (456, 0.08703882797784893),
 (457, 0.08703882797784893),
 (458, 0.21320071635561044),
 (459, 0.14625448482542613),
 (460, 0.06286946134619315),
 (461, 0.2727272727272727),
 (462, 0.1556997888323046),
 (463, 0.16116459280507606),
 (464, 0.061545745489666376),
 (465, 0.0),
 (466, 0.05504818825631803),
 (467, 0.06741998624632421),
 (468, 0.07312724241271307),
 (469, 0.11197850219117086),
 (470, 0.11396057645963795),
 (471, 0.08362420100070908),
 (472, 0.07312724241271307),
 (473, 0.07312724241271307),
 (474, 0.18463723646899913),
 (475, 0.05415303610738824),
 (476, 0.0),
 (477, 0.11009637651263605),
 (478, 0.06286946134619315),
 (479, 0.061545745489666376),
 (480, 0.18860838403857944),
 (481, 0.12060453783110546),
 (482, 0.0),
 (483, 0.0),
 (484, 0.061545745489666376),
 (485, 0.06917144638660747),
 (486, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.0),
 (490, 0.1421338109037403),
 (491, 0.059131239598908265),
 (492, 0.0),
 (493, 0.11826247919781653),
 (494, 0.11197850219117086),
 (495, 0.0),
 (496, 0.14625448482542613),
 (497, 0.07312724241271307),
 (498, 0.0),
 (499, 0.07537783614444091),
 (500, 0.13483997249264842),
 (501, 0.13834289277321493),
 (502, 0.0),
 (503, 0.0657951694959769),
 (504, 0.16116459280507606),
 (505, 0.09534625892455924),
 (506, 0.07537783614444091),
 (507, 0.07312724241271307),
 (508, 0.05096471914376255),
 (509, 0.0),
 (510, 0.05504818825631803),
 (511, 0.07106690545187015),
 (512, 0.07106690545187015),
 (513, 0.0),
 (514, 0.06741998624632421),
 (515, 0.09534625892455924),
 (516, 0.1160517706371319),
 (517, 0.07312724241271307),
 (518, 0.0),
 (519, 0.07106690545187015),
 (520, 0.0),
 (521, 0.07106690545187015),
 (522, 0.13834289277321493),
 (523, 0.059131239598908265),
 (524, 0.0),
 (525, 0.0),
 (526, 0.0),
 (527, 0.06741998624632421),
 (528, 0.0),
 (529, 0.0657951694959769),
 (530, 0.12309149097933275),
 (531, 0.09534625892455924),
 (532, 0.07106690545187015),
 (533, 0.0),
 (534, 0.0),
 (535, 0.13483997249264842),
 (536, 0.1421338109037403),
 (537, 0.18463723646899913),
 (538, 0.059131239598908265),
 (539, 0.0),
 (540, 0.18463723646899913),
 (541, 0.0),
 (542, 0.0),
 (543, 0.0),
 (544, 0.17407765595569785),
 (545, 0.0),
 (546, 0.0),
 (547, 0.07106690545187015),
 (548, 0.0),
 (549, 0.05504818825631803),
 (550, 0.19738550848793068),
 (551, 0.08703882797784893),
 (552, 0.0657951694959769),
 (553, 0.05698028822981897),
 (554, 0.14625448482542613),
 (555, 0.06428243465332249),
 (556, 0.0),
 (557, 0.0),
 (558, 0.1709408646894569),
 (559, 0.09090909090909091),
 (560, 0.13834289277321493),
 (561, 0.0),
 (562, 0.0657951694959769),
 (563, 0.1556997888323046),
 (564, 0.0),
 (565, 0.07537783614444091),
 (566, 0.0),
 (567, 0.0),
 (568, 0.0),
 (569, 0.09090909090909091),
 (570, 0.14625448482542613),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.16116459280507606),
 (576, 0.0657951694959769),
 (577, 0.08703882797784893),
 (578, 0.06741998624632421),
 (579, 0.08058229640253803),
 (580, 0.08058229640253803),
 (581, 0.15075567228888181),
 (582, 0.14625448482542613),
 (583, 0.07312724241271307),
 (584, 0.0778498944161523),
 (585, 0.2727272727272727),
 (586, 0.08362420100070908),
 (587, 0.12060453783110546),
 (588, 0.05802588531856595),
 (589, 0.2508726030021272),
 (590, 0.09534625892455924),
 (591, 0.1160517706371319),
 (592, 0.08362420100070908),
 (593, 0.059131239598908265),
 (594, 0.14625448482542613),
 (595, 0.06286946134619315),
 (596, 0.0),
 (597, 0.05802588531856595),
 (598, 0.0),
 (599, 0.06286946134619315),
 (600, 0.0),
 (601, 0.061545745489666376),
 (602, 0.06741998624632421),
 (603, 0.06741998624632421),
 (604, 0.06030226891555273),
 (605, 0.05415303610738824),
 (606, 0.059131239598908265),
 (607, 0.05802588531856595),
 (608, 0.1421338109037403),
 (609, 0.2631806779839076),
 (610, 0.0778498944161523),
 (611, 0.06030226891555273),
 (612, 0.08058229640253803),
 (613, 0.24174688920761409),
 (614, 0.07537783614444091),
 (615, 0.13483997249264842),
 (616, 0.0778498944161523),
 (617, 0.10660035817780521),
 (618, 0.08058229640253803),
 (619, 0.0657951694959769),
 (620, 0.0),
 (621, 0.05802588531856595),
 (622, 0.05698028822981897),
 (623, 0.07106690545187015),
 (624, 0.24174688920761409),
 (625, 0.0),
 (626, 0.08362420100070908),
 (627, 0.0),
 (628, 0.0),
 (629, 0.0),
 (630, 0.05698028822981897),
 (631, 0.0),
 (632, 0.07312724241271307),
 (633, 0.16116459280507606),
 (634, 0.0),
 (635, 0.13483997249264842),
 (636, 0.0),
 (637, 0.0),
 (638, 0.07537783614444091),
 (639, 0.1556997888323046),
 (640, 0.18090680674665818),
 (641, 0.09090909090909091),
 (642, 0.20225995873897262),
 (643, 0.0),
 (644, 0.06917144638660747),
 (645, 0.0),
 (646, 0.0),
 (647, 0.061545745489666376),
 (648, 0.0),
 (649, 0.2508726030021272),
 (650, 0.06030226891555273),
 (651, 0.08362420100070908),
 (652, 0.059131239598908265),
 (653, 0.12060453783110546),
 (654, 0.06428243465332249),
 (655, 0.06030226891555273),
 (656, 0.12856486930664499),
 (657, 0.06428243465332249),
 (658, 0.0),
 (659, 0.0),
 (660, 0.0),
 (661, 0.12309149097933275),
 (662, 0.0),
 (663, 0.05802588531856595),
 (664, 0.0),
 (665, 0.0),
 (666, 0.07312724241271307),
 (667, 0.06030226891555273),
 (668, 0.06741998624632421),
 (669, 0.14625448482542613),
 (670, 0.12309149097933275),
 (671, 0.13483997249264842),
 (672, 0.05698028822981897),
 (673, 0.07312724241271307),
 (674, 0.1315903389919538),
 (675, 0.0),
 (676, 0.0),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),
 (682, 0.0),
 (683, 0.0),
 (684, 0.06286946134619315),
 (685, 0.07106690545187015),
 (686, 0.0),
 (687, 0.06030226891555273),
 (688, 0.0),
 (689, 0.0),
 (690, 0.07106690545187015),
 (691, 0.0778498944161523),
 (692, 0.15075567228888181),
 (693, 0.08703882797784893),
 (694, 0.10660035817780521),
 (695, 0.061545745489666376),
 (696, 0.07537783614444091),
 (697, 0.0),
 (698, 0.07312724241271307),
 (699, 0.06286946134619315),
 (700, 0.1773937187967248),
 (701, 0.06741998624632421),
 (702, 0.05698028822981897),
 (703, 0.20225995873897262),
 (704, 0.05698028822981897),
 (705, 0.08058229640253803),
 (706, 0.0657951694959769),
 (707, 0.0),
 (708, 0.1556997888323046),
 (709, 0.05698028822981897),
 (710, 0.05415303610738824),
 (711, 0.1421338109037403),
 (712, 0.0),
 (713, 0.05802588531856595),
 (714, 0.0),
 (715, 0.06741998624632421),
 (716, 0.06428243465332249),
 (717, 0.0657951694959769),
 (718, 0.0),
 (719, 0.05698028822981897),
 (720, 0.0657951694959769),
 (721, 0.0),
 (722, 0.06428243465332249),
 (723, 0.18181818181818182),
 (724, 0.0),
 (725, 0.0),
 (726, 0.1556997888323046),
 (727, 0.10830607221477648),
 (728, 0.0),
 (729, 0.059131239598908265),
 (730, 0.0),
 (731, 0.15075567228888181),
 (732, 0.12309149097933275),
 (733, 0.0),
 (734, 0.06286946134619315),
 (735, 0.0),
 (736, 0.07106690545187015),
 (737, 0.06917144638660747),
 (738, 0.15075567228888181),
 (739, 0.07106690545187015),
 (740, 0.046524210519923545),
 (741, 0.0657951694959769),
 (742, 0.19069251784911848),
 (743, 0.1257389226923863),
 (744, 0.13483997249264842),
 (745, 0.0),
 (746, 0.12856486930664499),
 (747, 0.0),
 (748, 0.08362420100070908),
 (749, 0.0),
 (750, 0.0778498944161523),
 (751, 0.0),
 (752, 0.0),
 (753, 0.05698028822981897),
 (754, 0.0),
 (755, 0.0),
 (756, 0.0),
 (757, 0.0),
 (758, 0.06917144638660747),
 (759, 0.0),
 (760, 0.2611164839335468),
 (761, 0.1421338109037403),
 (762, 0.059131239598908265),
 (763, 0.0),
 (764, 0.1315903389919538),
 (765, 0.11826247919781653),
 (766, 0.13483997249264842),
 (767, 0.0),
 (768, 0.0778498944161523),
 (769, 0.16116459280507606),
 (770, 0.05802588531856595),
 (771, 0.04891159880445185),
 (772, 0.05698028822981897),
 (773, 0.0),
 (774, 0.1315903389919538),
 (775, 0.06286946134619315),
 (776, 0.0),
 (777, 0.0),
 (778, 0.050251890762960605),
 (779, 0.1160517706371319),
 (780, 0.0),
 (781, 0.05598925109558543),
 (782, 0.13834289277321493),
 (783, 0.1257389226923863),
 (784, 0.20225995873897262),
 (785, 0.0778498944161523),
 (786, 0.08362420100070908),
 (787, 0.07312724241271307),
 (788, 0.0),
 (789, 0.0),
 (790, 0.0),
 (791, 0.0),
 (792, 0.0),
 (793, 0.1421338109037403),
 (794, 0.1556997888323046),
 (795, 0.05598925109558543),
 (796, 0.06741998624632421),
 (797, 0.12856486930664499),
 (798, 0.08362420100070908),
 (799, 0.1315903389919538),
 (800, 0.06286946134619315),
 (801, 0.0),
 (802, 0.07312724241271307),
 (803, 0.0),
 (804, 0.05802588531856595),
 (805, 0.0),
 (806, 0.05698028822981897),
 (807, 0.10830607221477648),
 (808, 0.1160517706371319),
 (809, 0.0),
 (810, 0.0),
 (811, 0.0),
 (812, 0.0),
 (813, 0.0),
 (814, 0.11826247919781653),
 (815, 0.0778498944161523),
 (816, 0.0),
 (817, 0.0),
 (818, 0.0),
 (819, 0.0),
 (820, 0.08058229640253803),
 (821, 0.13834289277321493),
 (822, 0.07312724241271307),
 (823, 0.10497277621629561),
 (824, 0.2075143391598224),
 (825, 0.0),
 (826, 0.06741998624632421),
 (827, 0.1160517706371319),
 (828, 0.0),
 (829, 0.0),
 (830, 0.061545745489666376),
 (831, 0.2193817272381392),
 (832, 0.0),
 (833, 0.061545745489666376),
 (834, 0.0),
 (835, 0.06428243465332249),
 (836, 0.0),
 (837, 0.0),
 (838, 0.052486388108147805),
 (839, 0.06030226891555273),
 (840, 0.0),
 (841, 0.07537783614444091),
 (842, 0.0),
 (843, 0.05802588531856595),
 (844, 0.06030226891555273),
 (845, 0.07312724241271307),
 (846, 0.14625448482542613),
 (847, 0.1556997888323046),
 (848, 0.12856486930664499),
 (849, 0.06286946134619315),
 (850, 0.06741998624632421),
 (851, 0.13483997249264842),
 (852, 0.12060453783110546),
 (853, 0.06030226891555273),
 (854, 0.061545745489666376),
 (855, 0.08703882797784893),
 (856, 0.0),
 (857, 0.06286946134619315),
 (858, 0.06917144638660747),
 (859, 0.06286946134619315),
 (860, 0.0),
 (861, 0.11197850219117086),
 (862, 0.0),
 (863, 0.06917144638660747),
 (864, 0.059131239598908265),
 (865, 0.08058229640253803),

In [46]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]#top 5 similar movie

[(1103, 0.3458572319330373),
 (4991, 0.3344968040028363),
 (939, 0.30151134457776363),
 (2007, 0.30151134457776363),
 (3094, 0.30151134457776363)]

In [47]:
def recommend(movie):
    ind=new_df[new_df['title']==movie].index[0]
    sim=similarity[ind]
    top_five_movie=sorted(list(enumerate(sim)),reverse=True,key=lambda x:x[1])[1:6]
    for i in top_five_movie:
        print(new_df.iloc[i[0]].title)

In [48]:
new_df['title']

0                             Sankofa
1       The Great British Baking Show
2                        The Starling
3                        Je Suis Karl
4                               Jeans
                    ...
5327                          Zinzana
5328                           Zodiac
5329                       Zombieland
5330                             Zoom
5331                           Zubaan
Name: title, Length: 5332, dtype: object

In [49]:
recommend('Zubaan')

Myriam Fares: The Journey
Lara and the Beat
Si Doel the Movie 3
The Breakup Playlist
Bigflo & Oli: Hip Hop Frenzy

In [50]:
import pickle
pickle.dump(new_df.to_dict(),open('movies.pkl','wb'))

In [54]:
pickle.dump(similarity,open('similarity.pkl','wb'))